apiVersion: v1
kind: Service
metadata:
    name: "bytaks001-62c8"
    labels:
        app: "bytaks001-62c8"
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    selector:
        app: "bytaks001-62c8"