apiVersion: v1
kind: Service
metadata:
    name: "bytaks01cluster-1526"
    labels:
        app: "bytaks01cluster-1526"
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    selector:
        app: "bytaks01cluster-1526"